### ISSUE TITLE
Symbol’s function definition is void: map-apply

### ISSUE THREAD

**Issue by manuel-uberti** [raxod502/dumbparens#1]
Hi, 

I know this is still in development, but just so you know: after installing it, restarting Emacs results in:
```emacs-lisp
custom-initialize-reset: Symbol’s function definition is void: map-apply
```

**Comment by raxod502** [comment]
Oops.

**Comment by manuel-uberti** [comment]
Great, thank you.

And BTW, thanks for this project: I've always felt that Smartparens was way too much for what I need.
