### ISSUE TITLE
Question: how to make it work with go-mode and LSP

### ISSUE THREAD

**Issue by d1egoaz** [raxod502/dumbparens#3]
Hey 👋 

`dumbparens` works great in most of the modes, however, when I'm in a go-mode buffer and LSP, dumbparens stops working. (Typing an open paren does not insert a close paren)

I've double checked describing the key `(` in insert in a go-mode/LSP or for example fundamental-mode, both returned:
```
self-insert-command is an interactive function defined in C source
code.
```

I'm using latest dumbparens package and Emacs 28
```
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.4.0, NS appkit-2022.44 Version 11.3.1 (Build 20E241)) of 2021-05-20
```

Thanks

**Comment by raxod502** [comment]
Just FYI, this project isn't really finished or maintained. So I wouldn't expect everything to be in working order, and I don't have the bandwidth to make bugfixes and such.

That said, I had a look into this and can confirm the problem. It's probably a pretty straightforward fix. Take a read at https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Table-Internals.html, and note

> Syntax flags are encoded in higher order bits, starting 16 bits from the least significant bit.

So then if you look at the check

https://github.com/raxod502/dumbparens/blob/7bddec60258c48d561b6ae164a8d437d4b92db7f/dumbparens.el#L116

which is seeing if point is followed by whitespace, and check `(syntax-after (point))` in Go mode, you'll see it's 2097164, which is 0x20000c. In other words, Go mode is using some syntax flags, and Dumbparens isn't accounting for them when doing comparisons.

I think that everywhere we use `syntax-before` or `syntax-after`, we need to `logand` with `#xffff`.

**Comment by d1egoaz** [comment]
> That said, I had a look into this and can confirm the problem.

Thanks for looking into this.


I did read your answer, and I didn't understand 😅 ... yet, I'll read the links you posted and try to get an idea about how things work here and maybe send a patch.

**Comment by d1egoaz** [comment]
Isn't `syntax-class` the thing that does what you suggested?

```lisp
(defun syntax-class (syntax)
  "Return the code for the syntax class described by SYNTAX.

SYNTAX should be a raw syntax descriptor; the return value is a
integer that encodes the corresponding syntax class.  See Info
node `(elisp)Syntax Table Internals' for a list of codes.

If SYNTAX is nil, return nil."
  (and syntax (logand (car syntax) 65535)))
```

Although `(syntax-class (syntax-after (point)))` in a go file after a `(` returns `12 (#o14, #xc, ?\C-l)` (comment-end?), the same command in fundamental mode returns `(#o0, #x0, ?\C-@)` (whitespace?)

**Comment by raxod502** [comment]
Ah yes, great, we should indeed be using `syntax-class` in a bunch of places.

> the same command in fundamental mode

I think you might want `syntax-before`, not `syntax-after`, if point is _after_ the character of interest.

That said, different modes have various differences in how they construct their syntax tables. They're mostly similar enough that it's OK. In particular, note that in the line of code I highlighted above, both 0 and 12 are treated the same.
